### PR TITLE
Feature/set project config

### PR DESCRIPTION
**Pull request by TomvEtten**
added project command to set config of your project

### Overview
This pull request:

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Has tests?    | no
| BC breaks?    | no     
| Deprecations? | no 

### Summary
I added a diffy project:update command so we can update project configuration from versioned files inside our gitlab repo's  and use it in our pipelines..

### CODE REVIEW

**Comment by ygerasimov** [comment]
Thank you very much @TomvEtten !

**Comment by TomvEtten** [comment]
Thanks!, is it possible to tag a new release ?, so I can simply use phar file in my pipelines instead of building it in the pipeline :)

**Comment by ygerasimov** [comment]
@TomvEtten just pushed `0.1.9` tag

**Comment by TomvEtten** [comment]
Nice!

**Pull request merged**
